docs/markdown/code-preview.md
src/render/markdown/code-preview.ts

Med detta kan man i FKUI hitta på en custom tag för att påverka de E2E tester vi skriver, rent konkret vill jag stänga av testet som kollar att felsidan inte dyker upp för `ErrorPlugin` där felsidan ska visas.

feat: queryable example metadata

---

README.md
cypress/e2e/alt-container.cy.ts
docs/markdown/custom-containers.md
docs/markdown/my-alternative-text-file.md
etc/docs-manifest.md
src/document.ts
src/file-reader/front-matter-file-reader.ts
src/navigation/__snapshots__/generate-navtree.spec.ts.snap
src/render/markdown/include.ts

Lägger till att kunna ha en alternativ text från annan markdown fil. Förhoppningsvis är implementationen åt rätt håll.
Tar gärna feedback kring vad den ska heta. Har satt det som `alt`, som i alternative text. Andra tankar var `amend` som i amend text.
Kollade även upp hur dessa `:::` block benämns och kom fram till "custom container" genom att googla runt. Om ni har bättre koll tar jag gärna input där.
Frågetecken:
- Behöver vi felhantering i `alt`?
- Finns det nåt vettigt sätt att skriva tester för att säkerställa att `alt` fungerar?
Noterar också att vi inte verkar ha nån direkt dokumentation för `api` container, om inte jag har missat nåt.
Har inte åtgärdat det i denna PR, men bör antagligen läggas till inom snar framtid då det nu finns sida för dessa.

feat: add alternative text markdown container

---

src/style/core.scss

Rubrik i live exempel får felaktig styling. Denna fix löser så att live exempel inte tar med styling för rubriker från docs generator css.

docs: fix headers in live example (refs SFKUI-6577)

---

src/style/core.scss
src/style/css-variables.mjs

Styling för länkar -- vad jag försöker göra här är att stajla länkar i innehållet, men inte de som är rubriker, eller i menyer etc. 
se bild nedan
+ ändringar i package-lock.jason så den hänvisar till npmjs.org istället för npmjs.com

docs: link styling (refs SFKUI-6446)

---

src/runtime/navigation.ts
src/runtime/table-of-contents.ts

Fixar så att visning av aktiv header i innehållsförteckningen fungerar igen.
Verkade inte vara helt kompatibel med att ersätta innehåll vid navigering via sidmenyn så har lagt till att initiera toc även vid denna navigering. Samt att inte ersätta innehåll vid popstate event om det fortfarande är samma sida så att den inte ersätter state för toc.

fix: show active header in outline

---

src/runtime/breakpoints.ts
src/runtime/navigation.ts
src/runtime/table-of-contents.ts
src/style/_breakpoints.scss
src/style/_layout.scss
src/style/_outline.scss
templates/base.template.html

- `fix: do not render empty outline`
Sidor med `layout: component` men inga headings renderar fortfarande en tom outline med endast rubriken "Innehåll". Ändrar så att den inte renderas alls om inga headings finns.
- `fix: responsive table of contents`
Ändrar så att innehållsförteckningen fortfarande visas när aside staplas med övrigt innehåll.
Beteendet är satt så att outline automatiskt sätts som öppen när den ändras till stor storlek, och stängd i "mobil" storlek.
Då mycket av `details` elementet ligger i shadow var det svårt att ändra hur den fungerar/ser ut. Fick därav mecka lite i js för att få ihop det med breakpoints. Gör ont i att behöva duplicera breakpoint värdet så testar att fånga från css variables istället. Men tar gärna förslag på lösningar.
Efter:

fix: responsive table of contents

---

src/runtime/utils/index.ts
src/runtime/utils/memoize.spec.ts
src/runtime/utils/memoize.ts

Extracted from #48.
Allows for a simple way to cache the result of an expensive or slow computation or network call.
```ts
async function fetchAwesomeResource() {
const response = await fetch("/awesome/resource");
return await response.json();
}
const getAwesomeResource = memoize(fetchAwesomeResource);
const resource1 = await getAwesomeResource(); // uncached, calls fetchAwesomeResource()
const resource2 = await getAwesomeResource(); // cached, return cached result from previous call
```
When using parameters each set of parameters is cached individually:
```ts
function computeFibonacci(n) {
/* ... */
}
const fibonacci = memoize(computeFibonacci);
const first = fibonacci(10); // uncached, calls fibonacci(10)
const second = fibonacci(10); // cached, return cached result from previous call …
```

refactor: add memoization util

---

etc/index.api.md
src/assets/compile-script.ts
src/assets/compile-style.ts
src/assets/css-asset-processor.ts
src/assets/js-asset-processor.ts
src/generator.ts

Extracted from #48.
This is useful when dealing with ESM constructs such as having to use `import.meta.url`, e.g:
```diff
const bootstrapUrl = new URL("runtime-bootstrap.js", import.meta.url);
-        this.compileScript("bootstrap", fileURLToPath(bootstrapUrl), {
+        this.compileScript("bootstrap", bootstrapUrl, {
appendTo: "head",
});
```
Just a quality of life thing :)

feat(api): `compileScript` and `compileStyle` accepts URL parameter

---

src/processors/version-processor.ts

Extracted from https://github.com/Forsakringskassan/docs-generator/pull/48.
Only display hour:minute in the buildinfo. It seems excessive and unnecessary to include.
Before:
After:

fix: hide seconds from buildinfo

---

README.md
docs/markdown/index.md
docs/markdown/mermaid.md
etc/docs-manifest.md
src/navigation/__snapshots__/generate-navtree.spec.ts.snap
src/runtime/navigation.ts
src/style/_skeleton.scss
src/style/core.scss

Extracted from #48.
Fixes mermaid diagrams not being rendered after site navigation.
Additionally adds a skeleton element to prevent the graph source code from being visible while mermaid is loading.
(screen recordings are done with 10mbit network throttling simulate slow network, albeit I would consider that to be pretty good network conditions)
Before:
After:

fix: fix broken mermaid diagrams after navigation

---

etc/index.api.md
src/generator.ts
src/processor-context.ts
src/render/nunjucks-processor.ts
src/render/render.ts
src/render/template-loader.ts

Denna kan användas för att kolla om en template existerar. I #73 vill jag använda den för att inte bryta bakåtkompatibilitet men kan se fler use cases där man renderar ut innehåll bara om det finns en template (dvs där default är att inget renderas).
Denna är markerad som intern men notera att den också är exponerad i `ProcessorContext` så den kan fortfarande nyttjas även av externa processorer.

refactor: internal `hasTemplate`

---

etc/index.api.md
src/assets/compile-script.ts
src/assets/js-asset-processor.ts
src/compile-processor-runtime.spec.ts
src/compile-processor-runtime.ts
src/generator.ts
src/processor.ts

Detta är lite fränt, nu kan man använda `define: { ... }` från som processor för att kompilera sin runtime asset med config från konsumenten \o/
Konsument:
```ts
awesomeProcessor({
superDuperOption: "foobar",
}),
```
och i `awesomeProcessor`:
```ts
runtime: [
{
src: "src/runtime/awesome.ts",
buildOptions: {
define: {
SUPER_DUPER_OPTION: JSON.stringify(superDuperOption),
},
},
]
```
och sist då `runtime/awesome.ts`:
```ts
/* man skulle kunna generera en processor-env.d.ts men någon måtta med augomagin får det väl vara? */
declare const SUPER_DUPER_OPTION: string;
const superDuperOption = SUPER_DUPER_OPTION;
console.log(superDuperOption);
// > foobar
```
Och då är ju frågan alla bör sälla: varför vill man göra det?
Jo, man kan exempelvis exponera ut paketets versionsnummer från konsumenten. …

feat: expose a limited set of esbuild options to js assets

---

docs/src/docs-theme.scss
src/sass/compile-sass-string.ts
src/sass/module-importer.ts

Resolves both  `~fancyPackage/src/foo.scss` and `fancyPackage/src/foo.css` paths

feat: sass module importer (refs SB-4982)

---

templates/partials/topnav.html

Currently the responsive menu flickers really badly when loading the FKUI documentation
> [!WARNING]
> The starting points of the videos are not 100% the same so don't focus on loading times. Look at the behaviour instead.
This is when running on localhost. Adding a minimal amount of throttling increases the time this is visible significantly. On anything less than 100mbit it is visible for multiple seconds.
**Before:**
**After:**
---
This mitigates another issue: when navigating the unstyled "more" menu is permanently left in place as the topnav script is not rerun and it does not use the newly loaded elements.

fix: make responsive menu hidden while page is loading

---

src/sass/module-importer.ts

Current moduleimporter did not solve imports like:
entry.scss
```css
@import "@fancyPackage/src/file1"
@import "./foo";
```
foo.scss
```css
@import "@fancyPackage/src/file2"
```
Using https://sass-lang.com/documentation/js-api/interfaces/fileimporter/
TODO

Rewrite module import

---

build.mjs
src/style/core.scss

Konsumenter utav docs-generator skall inte behöva dra in nödvändig styling för hilight-js, de skall inte bry sig om att det nyttjas öht. :-)
Denna raden går därmed att ta bort:
* https://github.com/Forsakringskassan/designsystem/blob/main/docs/src/docs-theme.scss#L8

feat: bundle highlight styling (refs SB-4982)

---

docs/markdown/containers/details.md
docs/markdown/containers/messagebox.md
etc/docs-manifest.md
src/navigation/__snapshots__/generate-navtree.spec.ts.snap
src/render/markdown/container-renderer.ts
src/render/markdown/container/details-container.spec.ts
src/render/markdown/container/details-container.ts
src/render/markdown/container/index.ts
src/render/markdown/container/messagebox-container.spec.ts
src/render/markdown/container/messagebox-container.ts
src/style/_messagebox.scss
src/style/css-variables.mjs

Stöd för expanderbara ytor med `<details>` elementet. Själva `<details>` och `<summary>` (titel) är ostylat men la på en grå bakgrund och border tills vidare. @krehnst återkommer med skiss för hur det bör se ut senare.
**Kollapsad:**
**Expanderad:**

feat: support <details> element in markdown content

---

src/runtime/topnav.ts

Click handlern kastar alltid en exception. Är inte riktigt säker på vad avsikten med funktionen är men jag får alltid in `<a>`  taggen som `event.target` så behöver inte leta upp den.
@dvitamin Missar jag något här?

fix: fix `cannot read property of null` when clicking on topnav

---

docs/processors/source-url.md
etc/index.api.md
generate-docs.mjs
package-lock.json
package.json
src/examples/get-example-import.ts
src/processors/source-url-processor.ts
src/utils/file-matcher.ts
src/utils/index.ts

Från ~6 sekunder per fil till några hundra millisekunder.
Flera saker som spelar in här. Tidigare så matchades komponentens namn mot `**/${name}.${ext}` för varje förekomst i varje fil. Det inkluderar hela `node_modules`.
Nu så cachas det i flera nivåer:
* Vid uppstart läses listan över filer in från disk. Det besparar oss från att läsa ut lista över filer från filsystemet för varje url som ska genereras. Listan har hårdkodat i sig att exkludera `node_modules`.
* Vid själva matchningen så cachas resultatet igen per filnamn, så om samma filnamn efterfrågas två gånger så blir resultatet cachat.
* Och relaterat är att det nu finns en parameter `sourceFiles` där man kan peka ut mer specifikt vilka filer det rör sig om. Vi behöver exempelvis inte ha med `coverage` rapporten i kandidater att …

fix: fix performance regression when using sourceUrlProcessor

---

package.json
src/runtime/code-preview.spec.ts

Resolves build issue from #73.
The `src/runtime` folder now gets a different config with JSDOM environment.

test: use different jest configuration for runtime

---

src/compile-example.ts
src/vendor/compile-vendor.ts

Så fungerar prop validation osv som det ska.
Och så här blir det i FKUI:

fix: build examples in development mode

---

docs/navigation/index.md
docs/smoketest/index.md
docs/smoketest/table.md
etc/docs-manifest.md
etc/index.api.md
src/generator.ts
src/navigation/__snapshots__/generate-navtree.spec.ts.snap
src/navigation/generate-navtree.spec.ts
src/navigation/generate-navtree.ts
src/navigation/sort-navigation-tree.spec.ts
src/processors/topnav-processor.spec.ts
src/processors/topnav-processor.ts
templates/partials/topnav.html

Navigeringsrättningen ska brytas ut till egen PR. Resten är för att visa hur tabellen beter sig.

docs: add hidden smoketest for table

---

docs/markdown/containers/messagebox.md
src/style/_messagebox.scss
src/style/css-variables.mjs

lite justeringar i meddelanderutor
- code-taggar synns bättre inuti meddelanderutor
- hörnradie
- details använder samma typ av pilar som i navigering

fix: code in messagebox and messagebox styling

---

docs/markdown/code-preview/code-preview.md
docs/markdown/code-preview/javascript.md
docs/processors/version.md
etc/docs-manifest.md
src/examples/generate-example.ts
src/examples/index.ts
src/examples/transform-code.spec.ts
src/examples/transform-code.ts
src/navigation/__snapshots__/generate-navtree.spec.ts.snap
src/render/markdown/code-preview.ts

Möjliggör att man strippar bort delar av exempelkoden från vad som syns för läsaren:
````md
```ts
import { Foobar } from "foobar";
/* --- cut above --- */
const foobar = new Foobar();
```
````
Det som syns när det renderas sen ("Visa kod"):
```ts
const foobar = new Foobar();
```
Även eslint kommentarer strippas bort så om man behöver kan man köra `/* eslint-disable foobar */` utan att det syns för läsaren.
Syftet är att kunna kompilera och linta exempel utan att alltid behöva visa alla stegen. Exempelvis kan importen av `Foobar` ovan vara överflödig men behövs för att kunna kompilera.
Rekommenderar att läsa PRs i omvänd ordning, dvs börja med PR 4 och ta det därifrån. De mergas däremot i denna ordningen.

PR 2/4: source code stripping (compilable and lintable examples)

---

docs/processors/extract-examples.md
etc/docs-manifest.md
etc/index.api.md
src/index.ts
src/navigation/__snapshots__/generate-navtree.spec.ts.snap
src/processors/extract-examples-processor.ts
src/processors/index.ts

Låter oss extrahera ut exempel till separata filer så man lättare kan kompilera och linta filerna.
Givet `docs/foo/bar.md` med:
````md
```ts
const x = "foo";
const y = x + 1;
```
````
Och konfigurationen:
```ts
extractExamplesProcessor({
output: "docs/examples",
});
```
Så får man:
```
docs/examples/docs/foo/bar.md/example-1.ts
```
Den filen man kan sen linta och kompilera.
Gör man det i FKUI så får man:
* 39st eslint fel (efter att jag stängt av regler som `no-console`, `no-unused-vars` osv)
* ~69st~ kompileringsfel (en del exempel har rätt så allvarliga typos). **EDIT:** Om man fixar de 69 felen som är så allvarliga att `tsc` ballar ur helt så får man ca 250st nya fel :partying_face: 
Rekommenderar att läsa PRs i omvänd ordning, dvs börja med PR 4 och ta det därifrån. De mergas däremot …

PR 3/4: new extractExamplesProcessor (compilable and lintable examples)

---

internal/plugin-vue3/src/generate-code.ts
src/render/render.ts
src/render/template-render-error.spec.ts
src/render/template-render-error.ts

Den här ändringen gör inget mer än att göra fel från rendering mer begripliga genom att ta bort allt brus. Man ser inte längre vilken mall (och vilken rad/kolumn i mallen) men personligen tycker jag det är irrelevant (men ni behöver inte hålla med)
**Från**:
```
When running processor "nunjucks-renderer":
Error: Failed to render "docs/functions/cypress/pageobjects/FProgressbarPageObject/FProgressbarPageObject-progress-status.md": (/path/to/project/node_modules/@forsakringskassan/docs-generator/templates/article.template.html) [Line 8, Column 3]
Error: Errors occured when trying to parse docs/functions/cypress/pageobjects/FProgressbarPageObject/FProgressbarPageObject-progress-status.vue.
at render (/path/to/project/node_modules/@forsakringskassan/docs-generator/dist/index.js:2020:11)
at …
```

fix: more readable and usable error message when a render error occurs

---

internal/plugin-vue3/package.json
internal/plugin-vue3/src/generate-code.ts
package-lock.json
src/examples/generate-example.ts

Utökning av #154, om det är ett lokalt bygge (skiljt från CI) så hanteras fel från Vue's compiler och presenteras istället i runtime. Bygger man i CI miljö så får man fel som tidigare, dvs det stoppar bygget.
Motiveringen är att det ska vara smidigare när man aktivt sitter och skriver dokumentation. Typiskt exempel kan vara om man skapar upp en tom placeholder fil tills vidare men vill bygga och se resultatet av resten man skrivit.

fix: show vue compiler errors runtime during local builds

---

src/style/core.scss

Fixar font-storlek och understrykning för kod-block i rubriker.
Före:
Efter:
Sido effekt, då padding och marginal sätts till 0 så linjerar även rubriker som börjar med ett kod-block korrekt.

fix: correct font-size and text-decoration for code block in heading

---

src/utils/parse-import.ts

Potential fix for [https://github.com/Forsakringskassan/docs-generator/security/code-scanning/5](https://github.com/Forsakringskassan/docs-generator/security/code-scanning/5)
To fix the issue, we need to ensure that all instances of HTML comments are removed from the input string. We can achieve this by applying the regular expression replacement repeatedly until no more replacements can be performed. This approach ensures that all HTML comments are effectively removed, preventing any potential injection vulnerabilities.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 5: Incomplete multi-character sanitization

---

docs/configuration/index.md
docs/configuration/scripts.md
etc/docs-manifest.md
etc/index.api.md
src/assets/asset-info.ts
src/assets/compile-options.ts
src/assets/compile-script.spec.ts
src/assets/compile-script.ts
src/assets/css-asset-processor.ts
src/assets/js-asset-processor.ts
src/generator.ts
src/navigation/__snapshots__/generate-navtree.spec.ts.snap
src/processor-context.ts
src/render/render-options.ts
src/render/render.ts
templates/base.template.html

Ska skriva lite dokumentation för det här innan merge men man kan börja granska koden.
Det är två relaterade saker vi löser här:
1. Idag om man importerar `@fkui/vue` från ett script som kompileras med `compileScript()` så byggs det som CJS med `require()` vilket då inte längre lirar så vendors nu är ESM. Det har vi inte själva märkt då vi inte importerar `@fkui/vue` där.
2. Vi har problem att `setup()` kan anropas före alla script körts klart, det märks tydligare nu efter punkt 1 är löst så alla `<script type="module">` alltid implicit är `defer` och då körs de i fel ordning.
Dels så rättar denna så allt byggs som ESM men den lägger också till stöd för att lägga till egna scripts i importmap, det löser så man från `setup()` kan importera och vänta på andra script (med eller utan …

compileScripts(), esm och importmaps

---

docs/processors/search.md
etc/docs-manifest.md
etc/index.api.md
etc/markdown.api.md
src/document/document-attributes.ts
src/file-reader/front-matter-file-reader.ts
src/file-reader/navigation-file-reader.ts
src/navigation/__snapshots__/generate-navtree.spec.ts.snap
src/navigation/generate-navtree.spec.ts
src/processors/redirect/redirect-processor.ts
src/render/inline-tags/link.spec.ts
src/runtime/search.ts
src/search/generate-index.spec.ts
src/search/generate-index.ts
src/search/search-entry.ts
src/search/search-index.ts
src/search/search-processor.ts
src/utils/create-mock-document.ts

Bryter ut från #196 
---
Stöd för att lägga till extra söktermer på sidor:
Som exempel:
```diff
title: Tabell
status: Produktionsklar
layout: component
sortorder: 1
+search:
+    terms:
+        - Table
component:
- FDataTable
- FInteractiveTable
- FTableColumn
```
Då plockar sökindex upp att "table" också ska leda till denna sidan.
Framtida förbättring: dölj dubletter från sökresultat, exempelvis "tab" matchar både "Tabell" (sidnamnet) och "table" (term), då behöver vi inte visa båda.
---
Har lagt in lite rudimentär dokumentation över hur det fungerar.

feat: support search.terms to provide additional search terms

---

generate-docs.mjs
package-lock.json
package.json
src/generator.ts
src/i18n/en.json
src/i18n/sv.json
src/render/render-options.ts
src/render/render.ts
templates/base.template.html
templates/component.template.html
templates/partials/search-dialog.html
templates/partials/search-toolbar.html

Utbrutet från #196
---
Stöd för att översätta siten som är genererad med docs-generator. Idag är det en del hårdkodade texter så som "Innehåll", "Sök" osv, nu översätts texter baserat på vad man skickar in för `site.lang` inställning.
Det finns säkert texter som inte översätts än men stödet finns nu iaf.

feat: support translation with i18next

---

src/file-reader/vue-file-reader/find-translations.spec.ts
src/file-reader/vue-file-reader/find-translations.ts

fix: find doccomment attached to variable from `$t()`

---

src/render/markdown/code-preview.ts

Given markdown input:
````md
```html name=base
<p>lorem ipsum</p>
```
```html compare=base
<div>
<p>lorem ipsum</p>
</div>
```
````
The following is rendered:
**Before:**
```diff
-<p>lorem ipsum</p>
+<div>
+  <p>lorem ipsum</p>
+</div>
```
**After:**
```diff
+<div>
<p>lorem ipsum</p>
+</div>
```

fix: ignore whitespace in generated diffs

---

src/runtime/navigation.ts
src/style/_navigation.scss

Löser inte hela problemet, jag tror att vi måste göra om hela konceptet från scratch men får nog dubbelkolla med @johancarnegard och @niklasfk hur det ska fungera egentligen. Det finns flera olika scenarion att ha i beaktning:
* [Sida](https://designsystem.forsakringskassan.se/latest/components/) med lång meny, kort innehåll
* [Sida](https://designsystem.forsakringskassan.se/latest/styles/colors.html) med kort meny, långt innehåll
* [Sida](https://designsystem.forsakringskassan.se/latest/components/flabel.html) med lång meny, långt innehåll
* [Sida](https://designsystem.forsakringskassan.se/latest/guides/) med kort meny, kort innehåll
* Fönsterstorlek där meny inte får plats på höjden från början
* Fönsterstorlek där meny alltid får plats (aldrig scrollbar)
Footer beter sig väldigt udda …

scrollbar fixes

---

src/render/markdown/__snapshots__/paragraph.spec.ts.snap
src/render/markdown/paragraph.spec.ts
src/render/markdown/paragraph.ts

Trodde ändringen i 0fe71ac skulle vara ganska harmlös men den har ju sönder listor (men ingen skriker?)
Reagerade på att listan i @MCFK's [PR ser konstig ut](https://forsakringskassan.github.io/designsystem/pr-preview/pr-421/functions/plugins/formatplugin.html).
Givet:
```md
* foo
* bar
* baz
```
Förväntad HTML:
```html
<ul>
<li>foo</li>
<li>bar</li>
<li>baz</li>
</ul>
```
Istället får man:
```html
<ul>
<li><p class="docs-paragraph">foo</p></li>
<li><p class="docs-paragraph">bar</p></li>
<li><p class="docs-paragraph">baz</p></li>
</ul>
```
Denna bugfixen korrigerar det, nu renderas bara "riktiga" stycken med `<p>`.

fix: fix list items being rendered with paragraph tag

---

.github/workflows/build.yml

Removed node 21 since it´s no longer supporter. Soon 18 will be unsupported and 24 released(current).

ci: change build to supported node versions (fixes SFKUI-0000)

---

README.md
cypress.config.ts
docs/layout/overriding-templates.md
docs/markdown/api/vue.md
docs/markdown/containers/details.md
docs/markdown/containers/messagebox.md
docs/navigation/index.md
docs/processors/cookie.md
docs/processors/extract-examples.md
docs/processors/manifest.md
docs/processors/motd.md
docs/processors/search.md
docs/processors/source-url.md
docs/processors/topnav.md
docs/processors/version.md
etc/index.api.md
generate-docs.mjs
src/generator.ts
src/utils/normalize-path.ts

Passar in sökvägen till katalogen man vill bygga från. Underlättar för att skapa sökvägar relativa till den katalogen istället för att jobba med absoluta sökvägar.
Som vanligt är Windows det stora problemet därav hacken med att försöka normalizera. Provkörs i fjärrskrivbort med MSYS2, Git Bash och Powershell och vad jag kan se så får man ut ok resultat från detta. (`fs.stat(this.cwd)` gav korrekt resultat)
Fungerar om man inte passar in sökvägen men då får man en varning om deprekerat beteende.

feat: `Generator()` constructor takes `import.meta.url`
